GET http://localhost:3000/users/54674





POST http://localhost:3000/users
Content-Type: application/json

{
    "firstname": "John",
    "lastName": "Doe",
    "email": "john@doe.com",
    "password": "Password1"
}